# Generated by Django 4.2 on 2023-05-02 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0002_rename_user_myuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUser',
            new_name='User',
        ),
    ]
