# Generated by Django 4.2 on 2023-05-03 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0004_remove_catalog_owner_remove_file_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='availability_change_date',
            field=models.DateTimeField(default=models.DateTimeField(default=datetime.datetime.now)),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='last_changed',
            field=models.DateTimeField(default=models.DateTimeField(default=datetime.datetime.now)),
        ),
        migrations.AlterField(
            model_name='file',
            name='availability_change_date',
            field=models.DateTimeField(default=models.DateTimeField(default=datetime.datetime.now)),
        ),
        migrations.AlterField(
            model_name='file',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='file',
            name='last_changed',
            field=models.DateTimeField(default=models.DateTimeField(default=datetime.datetime.now)),
        ),
        migrations.AlterField(
            model_name='section',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
