# Generated by Django 4.2 on 2023-05-04 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0011_alter_file_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='parent_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcatalogs', to='compiler.catalog'),
        ),
    ]
