# Generated by Django 4.1.7 on 2023-05-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0013_alter_statusdata_line_of_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusdata',
            name='line_of_error',
            field=models.PositiveIntegerField(),
        ),
    ]
