# Generated by Django 4.1.7 on 2023-05-08 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0015_alter_statusdata_line_of_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_end',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_start',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
