# Generated by Django 4.2 on 2023-05-08 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0017_alter_section_contents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CompilerUser',
        ),
    ]
