# Generated by Django 4.2 on 2023-05-09 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0018_rename_user_compileruser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompilerUser',
        ),
    ]
