# Generated by Django 4.2 on 2023-05-02 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('availability', models.BooleanField(default=True)),
                ('availability_change_date', models.DateTimeField(auto_now_add=True)),
                ('last_changed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('availability', models.BooleanField(default=True)),
                ('availability_change_date', models.DateTimeField(auto_now_add=True)),
                ('last_changed', models.DateTimeField(auto_now_add=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compiler.catalog')),
            ],
        ),
        migrations.CreateModel(
            name='SectionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('KOMPILUJE_SIE_Z_OSTRZEZENIAMI', 'Kompiluje się z ostrzeżeniami'), ('KOMPILUJE_SIE_BEZ_OSTRZEZEN', 'Kompiluje się bez ostrzeżeń'), ('NIE_KOMPILUJE_SIE', 'Nie kompiluje się')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PROCEDURA', 'Procedura'), ('KOMENTARZ', 'Komentarz'), ('DYREKTYWA_KOMPILATORA', 'Dyrektywa kompilatora'), ('DEKLARACJE_ZMIENNYCH', 'Deklaracje zmiennych'), ('WSTAWKA_ASM', 'Wstawka asemblerowa')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StatusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('line_of_error', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('section_start', models.PositiveIntegerField()),
                ('section_end', models.PositiveIntegerField()),
                ('contents', models.TextField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compiler.file')),
                ('parent_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='compiler.section')),
                ('section_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compiler.sectionstatus')),
                ('status_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compiler.statusdata')),
                ('type_of_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compiler.sectiontype')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compiler.user'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compiler.user'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='parent_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdirectories', to='compiler.catalog'),
        ),
    ]
